#!/bin/bash
 
# sourcehost: choose a mirror in your proximity!
HOST=ftp.halifax.rwth-aachen.de;
 
# destination directory
DEST=/mnt/disk/volume1/myweb/mirror/antix/
 
# Debian version(s) to mirror
DIST=stretch
 
# architecture
ARCH=amd64,i386
 
# log timestamp
logger -t mirror[$$] updating Debian mirror
 
su mirror -c \
 "debmirror ${DEST} \
 --slow-cpu \
 --getcontents \
 --nosource \
 --host=${HOST} \
 --root=/mxlinux/packages/antix/stretch/ \
 --dist=${DIST} \
 --section=main,non-free \
 --arch=${ARCH} \
 --method=rsync \
 --i18n \
 --include='/Translation-de.*' \
 --include='/Translation-en.*' \
 --exclude='/Translation-.*' \
 --rsync-options '-aIL --partial --bwlimit=400' \
 --nocleanup \
 --diff=none \
 --progress >>/mnt/disk/volume1/logs/debmirror.log 2>&1"
logger -t mirror[$$] finished updating Debian mirror

