#!/bin/bash
DEBMLOG=/mnt/disk/volume1/logs/debmirror.log
MIRRORDIR=/mnt/disk/volume1/myweb/mirror
#SECSIZE=$(du -hs $MIRRORDIR/debian-security)
#MINTSIZE=$(du -hs $MIRRORDIR/mint)
#LENNYSIZE=$(du -hs $MIRRORDIR/lenny)

if test -s $DEBMLOG
then
test -f $DEBMLOG.3.xz && mv $DEBMLOG.3.xz $DEBMLOG.4.xz
test -f $DEBMLOG.2.xz && mv $DEBMLOG.2.xz $DEBMLOG.3.xz
test -f $DEBMLOG.1.xz && mv $DEBMLOG.1.xz $DEBMLOG.2.xz
test -f $DEBMLOG.0 && mv $DEBMLOG.0 $DEBMLOG.1 && xz $DEBMLOG.1
mv $DEBMLOG $DEBMLOG.0
cp /dev/null $DEBMLOG
chmod 666 $DEBMLOG
fi

echo "!!!!!!!!!UPDATE ALLER MIRRORS!!!!!!!!!!" 2>&1 | tee -a $DEBMLOG
echo "---------------------------------------" 2>&1 | tee -a $DEBMLOG
echo "######### 1. Debian Security ##########" 2>&1 | tee -a $DEBMLOG
date 2>&1 | tee -a $DEBMLOG
/etc/mirupdates
echo "######### 2. Linux Mint ###############" 2>&1 | tee -a $DEBMLOG
date 2>&1 | tee -a $DEBMLOG
/etc/mirmint
echo "######### 3. Debian Lenny #############" 2>&1 | tee -a $DEBMLOG 
date 2>&1 | tee -a $DEBMLOG
/etc/mirror
echo "######### 4. VirtualBox ###############" 2>&1 | tee -a $DEBMLOG 
date 2>&1 | tee -a $DEBMLOG
/etc/mirvirt
echo "######### 5. Spotify ##################" 2>&1 | tee -a $DEBMLOG 
date 2>&1 | tee -a $DEBMLOG
/etc/mirspotify
echo "######### 6. MXLinux ##################" 2>&1 | tee -a $DEBMLOG 
date 2>&1 | tee -a $DEBMLOG
/etc/mirmx
echo "######### 7. AntiX ####################" 2>&1 | tee -a $DEBMLOG
date 2>&1 | tee -a $DEBMLOG
/etc/mirantix
echo "######### 8. Debian ###################" 2>&1 | tee -a $DEBMLOG
date 2>&1 | tee -a $DEBMLOG
/etc/mirstretch
echo "######### 9. UBUNTU ###################" 2>&1 | tee -a $DEBMLOG
date 2>&1 | tee -a $DEBMLOG
/etc/mirdisco
echo "######## Calculate MIRROR SIZE ########" 2>&1 | tee -a $DEBMLOG
MIRSIZE=$(du -hs $MIRRORDIR)
NOW=$(date)
echo "$MIRSIZE" 2>&1 | tee -a $DEBMLOG
echo "Run: $NOW" 2>&1 | tee -a $DEBMLOG
echo "!!!!!!!!!!END MIRROR UPDATE!!!!!!!!!!!!" 2>&1 | tee -a $DEBMLOG
echo "#######################################" 2>&1 | tee -a $DEBMLOG
/etc/init.d/noflushd stop
noflushd -n 20 /dev/sda /dev/sdb
