#!/bin/bash
 
# sourcehost: choose a mirror in your proximity!
HOST=www.deb-multimedia.org;
 
# destination directory
DEST=/mnt/disk/volume1/myweb/mirror/debian-multimedia
 
# Debian version(s) to mirror
DIST=stable,testing,unstable,experimental
 
# architecture
ARCH=amd64,i386
 
# log timestamp
logger -t mirror[$$] updating deb-multimedia mirror
 
su mirror -c \
 "debmirror ${DEST} \
 --getcontents \
 --nosource \
 --host=${HOST} \
 --root=/deb \
 --dist=${DIST} \
 --section=main,non-free \
 --arch=${ARCH} \
 --method=rsync \
 --i18n \
 --include='/Translation-de.*' \
 --include='/Translation-en.*' \
 --exclude='/Translation-.*' \
 --rsync-options '-aIL --partial --bwlimit=400' \
 --progress \
 --verbose \
 --nocleanup >>/mnt/disk/volume1/logs/debmirror.log 2>&1"
logger -t mirror[$$] finished updating deb-multimedia mirror
