#!/bin/bash
 
# sourcehost: choose a mirror in your proximity!
HOST=archive.ubuntu.com;
 
# destination directory
DEST=/mnt/disk/volume1/myweb/mirror/disco
 
# Debian version(s) to mirror
DIST=disco,disco-security,disco-updates
 
# architecture
ARCH=amd64,i386
 
# log timestamp
logger -t mirror[$$] updating Ubuntu mirror
 
su mirror -c \
 "debmirror ${DEST} \
 --slow-cpu \
 --allow-dist-rename \
 --nosource \
 --host=${HOST} \
 --root=/ubuntu \
 --dist=${DIST} \
 --section=main,restricted,universe,multiverse \
 --arch=${ARCH} \
 --method=rsync \
 --i18n \
 --include='/Translation-de.*' \
 --include='/Translation-en.*' \
 --exclude='/Translation-.*' \
 --rsync-options '-aIL --partial --bwlimit=400' \
 --progress \
 --nocleanup >>/mnt/disk/volume1/logs/debmirror.log 2>&1"
logger -t mirror[$$] finished updating Ubuntu mirror
