#!/bin/bash
 
# sourcehost: choose a mirror in your proximity!
HOST=rsync-packages.linuxmint.com;
 
# destination directory
DEST=/mnt/disk/volume1/myweb/mirror/mint
 
# Debian version(s) to mirror
DIST=cindy
 
# architecture
ARCH=amd64,i386
 
# log timestamp
logger -t mirror[$$] updating Linux Mint mirror
 
su mirror -c \
 "debmirror ${DEST} \
 --getcontents \
 --nosource \
 --allow-dist-rename \
 --slow-cpu \
 --host=${HOST} \
 --root=/packages \
 --dist=${DIST} \
 --section=main,upstream,import,backport,romeo \
 --arch=${ARCH} \
 --method=rsync \
 --i18n \
 --include='/Translation-de.*' \
 --include='/Translation-en.*' \
 --exclude='/Translation-.*' \
 --rsync-options '-aIL --partial --bwlimit=400' \
 --progress \
 --nocleanup >>/mnt/disk/volume1/logs/debmirror.log 2>&1"
logger -t mirror[$$] finished updating Linux Mint mirror
