#!/bin/bash
 
# sourcehost: choose a mirror in your proximity!
HOST=debian.inf.tu-dresden.de;
 
# destination directory
DEST=/mnt/disk/volume1/myweb/mirror/stretch
 
# Debian version(s) to mirror
DIST=stretch,buster,sid,stretch-updates,buster-updates
 
# architecture
ARCH=amd64,i386
 
# log timestamp
logger -t mirror[$$] updating Debian mirror
 
su mirror -c \
 "debmirror ${DEST} \
 --slow-cpu \
 --allow-dist-rename \
 --getcontents \
 --nosource \
 --host=${HOST} \
 --root=debian/ \
 --dist=${DIST} \
 --section=main,contrib,non-free,main/debian-installer,main/installer-i386,main/installer-amd64 \
 --arch=${ARCH} \
 --method=rsync \
 --i18n \
 --include='/Translation-de.*' \
 --include='/Translation-en.*' \
 --exclude='/Translation-.*' \
 --rsync-options '-aIL --partial --bwlimit=400' \
 --nocleanup \
 --progress \
 --di-dist=stretch,buster,sid \
 --di-arch=i386,amd64 \
 --rsync-extra=doc,tools,trace >>/mnt/disk/volume1/logs/debmirror.log 2>&1"
logger -t mirror[$$] finished updating Debian mirror

